# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74e12df5735cf6d7db0c06d8931b640f"
name = "Melo Pet and Garden Loyalty"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers,read_customers"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/api/proxy"
subpath = "custom-invoice"
prefix = "apps"

[customer.metafields.loyalty.document_type]
name = "Tipo de Documento"
type = "single_line_text_field"
access.admin = "merchant_read_write"

[customer.metafields.loyalty.document_number]
name = "Número de Documento"
type = "single_line_text_field"
access.admin = "merchant_read_write"

[customer.metafields.loyalty.first_name]
name = "Nombre"
type = "single_line_text_field"
access.admin = "merchant_read_write"

[customer.metafields.loyalty.last_name]
name = "Apellido"
type = "single_line_text_field"
access.admin = "merchant_read_write"

[customer.metafields.loyalty.birth_date]
name = "Fecha de Nacimiento"
type = "date"
access.admin = "merchant_read_write"

[customer.metafields.loyalty.gender]
name = "Género"
type = "single_line_text_field"
access.admin = "merchant_read_write"

[customer.metafields.loyalty.phone]
name = "Teléfono"
type = "single_line_text_field"
access.admin = "merchant_read_write"

[customer.metafields.loyalty.phone_country_code]
name = "Código de País del Teléfono"
type = "single_line_text_field"
access.admin = "merchant_read_write"

[customer.metafields.loyalty.province]
name = "Provincia"
type = "single_line_text_field"
access.admin = "merchant_read_write"

[customer.metafields.loyalty.district]
name = "Distrito"
type = "single_line_text_field"
access.admin = "merchant_read_write"

[customer.metafields.loyalty.corregimiento]
name = "Corregimiento"
type = "single_line_text_field"
access.admin = "merchant_read_write"

[customer.metafields.loyalty.wants_custom_invoice]
name = "Quiere Factura Personalizada"
type = "boolean"
access.admin = "merchant_read_write"
